apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-generator.fullname" . }}
  labels:
    {{- include "log-generator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "log-generator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "log-generator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name:  {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
          - name: LOG_RATE_IN_MILLISECONDS
            value: "{{ .Values.logRateInMilliseconds }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
