{{- if .Values.serviceMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "log-generator.fullname" . }}
  labels:
    {{- include "log-generator.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "log-generator.selectorLabels" . | nindent 6 }}
{{- end }}
